[2025-02-27T12:48:31.872+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-27T12:33:09.781503+00:00 [queued]>
[2025-02-27T12:48:31.888+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-27T12:33:09.781503+00:00 [queued]>
[2025-02-27T12:48:31.889+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2025-02-27T12:48:31.922+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-27 12:33:09.781503+00:00
[2025-02-27T12:48:31.931+0000] {standard_task_runner.py:57} INFO - Started process 2073 to run task
[2025-02-27T12:48:31.938+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'run_mapreduce_job', 'manual__2025-02-27T12:33:09.781503+00:00', '--job-id', '327', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpn7stkcm1']
[2025-02-27T12:48:31.944+0000] {standard_task_runner.py:85} INFO - Job 327: Subtask run_mapreduce_job
[2025-02-27T12:48:32.037+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-27T12:33:09.781503+00:00 [running]> on host 6fa12894bc34
[2025-02-27T12:48:32.161+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-02-27T12:48:32.224+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T12:33:09.781503+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T12:33:09.781503+00:00'
[2025-02-27T12:48:32.228+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-27T12:48:32.230+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i namenode         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar         -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=27/coingecko_raw.json         -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=27         -mapper "python3 /tmp/mapper.py"         -reducer "python3 /tmp/reducer.py"\n        ']
[2025-02-27T12:48:32.246+0000] {subprocess.py:86} INFO - Output:
[2025-02-27T12:48:33.815+0000] {subprocess.py:93} INFO - 2025-02-27 12:48:33,813 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-27T12:48:33.866+0000] {subprocess.py:93} INFO - 2025-02-27 12:48:33,865 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-27T12:48:33.867+0000] {subprocess.py:93} INFO - 2025-02-27 12:48:33,865 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-27T12:48:33.880+0000] {subprocess.py:93} INFO - 2025-02-27 12:48:33,879 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-27T12:48:34.026+0000] {subprocess.py:93} INFO - 2025-02-27 12:48:34,024 ERROR streaming.StreamJob: Error Launching job : Output directory hdfs://namenode:9000/user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=27 already exists
[2025-02-27T12:48:34.027+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-27T12:48:34.593+0000] {subprocess.py:97} INFO - Command exited with return code 5
[2025-02-27T12:48:34.615+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2025-02-27T12:48:34.625+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coingecko_ingestion_dag, task_id=run_mapreduce_job, execution_date=20250227T123309, start_date=20250227T124831, end_date=20250227T124834
[2025-02-27T12:48:34.655+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 327 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 5.; 2073)
[2025-02-27T12:48:34.705+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T12:48:34.744+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
